repos:
  - repo: local
    hooks:
      - id: api-lint
        name: api-lint
        entry: bash -c 'make lint'
        language: system
        always_run: true
        pass_filenames: false
      - id: api-format
        name: api-format
        entry: bash -c 'make format'
        language: system
        always_run: true
        pass_filenames: false
      - id: api-typecheck
        name: api-typecheck
        entry: bash -c 'make typecheck'
        language: system
        always_run: true
        pass_filenames: false
